"use client";

import { useMemo, useState, type FormEvent } from "react";
import { MapPin, Pencil, Plus, Store } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/ui/page-header";
import { KpiCard } from "@/components/ui/kpi-card";
import { StatusBadge } from "@/components/ui/status-badge";
import { Modal } from "@/components/ui/modal";
import { useSalesData } from "@/lib/sales-data-context";
import { useAuth } from "@/lib/auth-context";
import { analyzeLocationSales, filterSales, resolvePeriodRange, type Location } from "@/lib/sales";
import { formatPercent, formatYen } from "@/lib/format";

interface LocationDraft { code: string; name: string; address: string; phone: string; isActive: boolean; }
function draftFor(location?: Location): LocationDraft { return location ? { code: location.code, name: location.name, address: location.address, phone: location.phone, isActive: location.isActive } : { code: "", name: "", address: "", phone: "", isActive: true }; }

export function LocationManagement() {
  const { user } = useAuth();
  const { data, saveLocation, hasPermission } = useSalesData();
  const [editing, setEditing] = useState<Location | null | undefined>(undefined);
  const [draft, setDraft] = useState<LocationDraft>(draftFor());
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const currentSales = useMemo(() => filterSales(data.sales, { dateRange: resolvePeriodRange("currentMonth") }), [data.sales]);
  const previousSales = useMemo(() => filterSales(data.sales, { dateRange: resolvePeriodRange("previousMonth") }), [data.sales]);
  const monthKey = new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", timeZone: "Asia/Tokyo" }).format(new Date()).slice(0, 7);
  const rows = useMemo(() => analyzeLocationSales(currentSales, data.locations, { previousSales, goals: data.goals, periodKey: monthKey }), [currentSales, previousSales, data.locations, data.goals, monthKey]);
  const rowById = new Map(rows.map((row) => [row.id, row]));
  const canManage = hasPermission("locations:manage");
  const inputClass = "mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20";

  function openForm(location?: Location) { setEditing(location ?? null); setDraft(draftFor(location)); setError(""); }
  async function handleSave(event: FormEvent) { event.preventDefault(); if (!user) return; setError(""); if (!draft.code.trim() || draft.name.trim().length < 2) { setError("店舗コードと店舗名を入力してください。"); return; } const timestamp = new Date().toISOString(); const id = editing?.id ?? crypto.randomUUID(); const location: Location = { id, organizationId: user.organizationId, locationId: id, code: draft.code.trim().toUpperCase(), name: draft.name.trim(), address: draft.address.trim(), phone: draft.phone.trim(), isActive: draft.isActive, createdAt: editing?.createdAt ?? timestamp, createdBy: editing?.createdBy ?? user.uid, updatedAt: timestamp, updatedBy: user.uid }; setSaving(true); try { await saveLocation(location); toast.success(editing ? "店舗情報を更新しました" : "店舗を登録しました"); setEditing(undefined); } catch (caught) { setError(caught instanceof Error ? caught.message : "保存できませんでした。"); } finally { setSaving(false); } }

  return <div><PageHeader title="店舗管理・店舗別分析" eyebrow="マスタ・分析" description="複数店舗の基本情報と、今月の売上・客単価・目標達成率を管理します。" actions={canManage ? <button type="button" onClick={() => openForm()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white transition active:scale-[0.98] hover:bg-blue-700 motion-reduce:transition-none"><Plus className="size-4" aria-hidden="true" />店舗登録</button> : null} />
    <section className="grid gap-4 lg:grid-cols-3">{data.locations.map((location) => { const row = rowById.get(location.id); return <article key={location.id} className="rounded-2xl border border-black/[0.06] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Store className="size-5" aria-hidden="true" /></span><StatusBadge status={location.isActive ? "active" : "inactive"} label={location.isActive ? "有効" : "無効"} tone={location.isActive ? "success" : "neutral"} /></div><div className="mt-4 flex items-start justify-between gap-3"><div><span className="text-xs font-bold text-blue-700">{location.code}</span><h2 className="mt-1 text-lg font-bold">{location.name}</h2></div><button type="button" onClick={() => openForm(location)} disabled={!canManage} className="flex size-11 items-center justify-center rounded-xl text-slate-500 hover:bg-blue-50 hover:text-blue-700 disabled:opacity-30" aria-label={`${location.name}を編集`}><Pencil className="size-4" aria-hidden="true" /></button></div><p className="mt-2 min-h-10 text-sm leading-5 text-slate-500"><MapPin className="mr-1 inline size-3.5" aria-hidden="true" />{location.address || "住所未登録"}</p><dl className="mt-5 grid grid-cols-2 gap-3 border-t border-slate-100 pt-4 text-sm"><div><dt className="text-xs text-slate-500">今月売上</dt><dd className="mt-1 font-bold tabular-nums">{formatYen(row?.netSalesYen ?? 0)}</dd></div><div><dt className="text-xs text-slate-500">取引件数</dt><dd className="mt-1 font-bold tabular-nums">{row?.transactionCount ?? 0}件</dd></div><div><dt className="text-xs text-slate-500">平均客単価</dt><dd className="mt-1 font-bold tabular-nums">{formatYen(row?.averageOrderYen ?? 0)}</dd></div><div><dt className="text-xs text-slate-500">前月比</dt><dd className={`mt-1 font-bold tabular-nums ${(row?.previousPeriodChangePercent ?? 0) >= 0 ? "text-emerald-700" : "text-red-700"}`}>{formatPercent(row?.previousPeriodChangePercent)}</dd></div></dl><div className="mt-4 rounded-xl bg-slate-50 p-3"><div className="flex justify-between text-xs"><span className="text-slate-500">目標達成率</span><strong className="tabular-nums">{formatPercent(row?.achievementRatePercent)}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, Math.max(0, row?.achievementRatePercent ?? 0))}%` }} /></div></div></article>; })}</section>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{rows.slice(0, 4).map((row) => <KpiCard key={row.id} title={`${row.rank}位 · ${row.name}`} value={formatYen(row.netSalesYen)} icon={<Store className="size-5" />} tone={row.rank === 1 ? "blue" : "cyan"} helper={`目標 ${formatYen(row.targetYen)} · ${formatPercent(row.achievementRatePercent)}`} />)}</section>
    <Modal open={editing !== undefined} onClose={() => setEditing(undefined)} title={editing ? "店舗を編集" : "店舗を登録"} size="lg" footer={<><button type="button" onClick={() => setEditing(undefined)} className="min-h-11 rounded-xl border border-slate-200 px-4 text-sm font-bold">キャンセル</button><button type="submit" form="location-form" disabled={saving} className="min-h-11 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white disabled:opacity-50">{saving ? "保存中…" : "保存"}</button></>}><form id="location-form" onSubmit={handleSave} className="grid gap-4 sm:grid-cols-2">{error ? <div role="alert" className="sm:col-span-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div> : null}<label className="text-sm font-semibold">店舗名<input value={draft.name} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} autoFocus required className={inputClass} /></label><label className="text-sm font-semibold">店舗コード<input value={draft.code} onChange={(event) => setDraft((current) => ({ ...current, code: event.target.value }))} required className={`${inputClass} uppercase`} /></label><label className="text-sm font-semibold sm:col-span-2">住所<input value={draft.address} onChange={(event) => setDraft((current) => ({ ...current, address: event.target.value }))} className={inputClass} /></label><label className="text-sm font-semibold">電話番号<input type="tel" value={draft.phone} onChange={(event) => setDraft((current) => ({ ...current, phone: event.target.value }))} className={inputClass} /></label><label className="text-sm font-semibold">状態<select value={draft.isActive ? "active" : "inactive"} onChange={(event) => setDraft((current) => ({ ...current, isActive: event.target.value === "active" }))} className={inputClass}><option value="active">有効</option><option value="inactive">無効</option></select></label></form></Modal>
  </div>;
}
