"use client";

import { useMemo, useState } from "react";
import { Database, FlaskConical, History, RotateCcw, ShieldCheck, UserCog } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/ui/page-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { useAuth } from "@/lib/auth-context";
import { useSalesData } from "@/lib/sales-data-context";
import { dateTimeFormatter } from "@/lib/format";
import { hasPermission as roleHasPermission, type Permission, type UserRole } from "@/lib/sales";

const roleLabels: Record<UserRole, string> = { admin: "管理者", manager: "マネージャー", user: "一般ユーザー", viewer: "閲覧のみ" };
const permissionRows: { label: string; permission: Permission }[] = [
  { label: "全売上の閲覧", permission: "sales:read:any" }, { label: "自分の売上の閲覧", permission: "sales:read:own" }, { label: "売上登録", permission: "sales:create" }, { label: "全売上の編集", permission: "sales:update:any" }, { label: "自分の売上の編集", permission: "sales:update:own" }, { label: "取消", permission: "sales:cancel" }, { label: "返金", permission: "sales:refund" }, { label: "商品管理", permission: "products:manage" }, { label: "顧客管理", permission: "customers:manage" }, { label: "担当者管理", permission: "staff:manage" }, { label: "店舗管理", permission: "locations:manage" }, { label: "目標管理", permission: "goals:manage" }, { label: "分析", permission: "analytics:read" }, { label: "レポート", permission: "reports:read" }, { label: "CSV出力", permission: "csv:export" }, { label: "CSV取込", permission: "csv:import" }, { label: "設定変更", permission: "settings:manage" }, { label: "監査ログ", permission: "audit:read" },
];

export function SettingsPage() {
  const { user, firebaseEnabled, setDemoRole } = useAuth();
  const { data, resetDemo, hasPermission } = useSalesData();
  const [resetOpen, setResetOpen] = useState(false);
  const [auditSearch, setAuditSearch] = useState("");
  const audits = useMemo(() => data.auditLogs.filter((log) => !auditSearch || `${log.actorName}${log.summary}${log.entityType}`.toLocaleLowerCase("ja-JP").includes(auditSearch.toLocaleLowerCase("ja-JP"))).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 100), [data.auditLogs, auditSearch]);
  if (!user) return null;

  async function handleReset() { await resetDemo(); setResetOpen(false); toast.success("デモデータを初期状態に戻しました"); }
  return <div><PageHeader title="設定・権限・監査" eyebrow="システム" description="利用中の組織・権限・データ接続を確認し、重要な操作履歴を追跡します。" />
    <section className="grid gap-4 lg:grid-cols-3"><InfoCard icon={<UserCog className="size-5" />} title="ログインユーザー"><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs text-slate-500">名前</dt><dd className="mt-1 font-bold">{user.name}</dd></div><div><dt className="text-xs text-slate-500">メール</dt><dd className="mt-1 break-all text-slate-700">{user.email}</dd></div><div><dt className="text-xs text-slate-500">権限</dt><dd className="mt-1"><StatusBadge status={user.role} label={roleLabels[user.role]} tone={user.role === "admin" ? "primary" : user.role === "viewer" ? "neutral" : "info"} /></dd></div></dl></InfoCard><InfoCard icon={<Database className="size-5" />} title="組織・データ"><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs text-slate-500">組織</dt><dd className="mt-1 font-bold">{data.organization.name}</dd></div><div><dt className="text-xs text-slate-500">店舗数</dt><dd className="mt-1 font-bold tabular-nums">{data.locations.length}店舗</dd></div><div><dt className="text-xs text-slate-500">接続</dt><dd className="mt-1"><StatusBadge status={user.isDemo ? "demo" : firebaseEnabled ? "firebase" : "offline"} label={user.isDemo ? "ブラウザ内デモ" : firebaseEnabled ? "Cloud Firestore" : "未設定"} tone={user.isDemo ? "warning" : firebaseEnabled ? "success" : "danger"} /></dd></div></dl></InfoCard><InfoCard icon={<ShieldCheck className="size-5" />} title="セキュリティ"><ul className="mt-4 space-y-2 text-sm leading-6 text-slate-600"><li>・組織IDでテナントを分離</li><li>・4段階のロール権限</li><li>・取消後の金額編集を禁止</li><li>・売上変更を監査ログへ記録</li><li>・CSV数式注入を防止</li></ul></InfoCard></section>
    {user.isDemo ? <section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><FlaskConical className="mt-0.5 size-5 text-amber-700" aria-hidden="true" /><div><h2 className="font-bold text-amber-950">デモ環境</h2><p className="mt-1 text-sm leading-6 text-amber-900">権限を切り替えて表示・操作制御を確認できます。変更はこのブラウザだけに保存されます。</p></div></div><button type="button" onClick={() => setResetOpen(true)} className="inline-flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-xl border border-amber-300 bg-white px-4 text-sm font-bold text-amber-900"><RotateCcw className="size-4" aria-hidden="true" />初期データへ戻す</button></div><label className="mt-4 block max-w-sm text-sm font-bold text-amber-950">体験する権限<select value={user.role} onChange={(event) => setDemoRole(event.target.value as UserRole)} className="mt-1.5 min-h-11 w-full rounded-xl border border-amber-300 bg-white px-3 text-sm text-slate-900"><option value="admin">管理者</option><option value="manager">マネージャー</option><option value="user">一般ユーザー</option><option value="viewer">閲覧のみ</option></select></label></section> : null}
    <section className="mt-6 overflow-hidden rounded-2xl border border-black/[0.06] bg-white shadow-sm" aria-labelledby="permissions-title"><div className="border-b border-slate-100 px-5 py-4 sm:px-6"><h2 id="permissions-title" className="font-bold">権限マトリクス</h2><p className="mt-1 text-xs text-slate-500">画面制御と同じ権限モデルをFirestore Security Rulesでも検証します。</p></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-center text-xs"><thead className="bg-slate-50 font-bold text-slate-500"><tr><th className="px-5 py-3 text-left">操作</th>{Object.values(roleLabels).map((label) => <th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{permissionRows.map((row) => <tr key={row.permission}><th className="px-5 py-3 text-left font-semibold text-slate-700">{row.label}</th>{(["admin", "manager", "user", "viewer"] as UserRole[]).map((role) => <td key={role} className="px-3 py-3"><PermissionMark role={role} permission={row.permission} /></td>)}</tr>)}</tbody></table></div></section>
    <section className="mt-6 overflow-hidden rounded-2xl border border-black/[0.06] bg-white shadow-sm" aria-labelledby="audit-title"><div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex items-center gap-2"><History className="size-5 text-blue-700" aria-hidden="true" /><div><h2 id="audit-title" className="font-bold">監査ログ</h2><p className="mt-0.5 text-xs text-slate-500">登録・編集・取消・返金・マスタ・目標の変更履歴</p></div></div><input type="search" value={auditSearch} onChange={(event) => setAuditSearch(event.target.value)} placeholder="操作者・内容で検索" className="min-h-10 rounded-xl border border-slate-300 px-3 text-sm outline-none focus:border-blue-500" /></div>{hasPermission("audit:read") ? <div className="max-h-[34rem] divide-y divide-slate-100 overflow-y-auto">{audits.map((log) => <article key={log.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[9rem_minmax(0,1fr)_10rem] sm:items-start sm:px-6"><time className="text-xs tabular-nums text-slate-500">{dateTimeFormatter.format(new Date(log.createdAt))}</time><div><strong className="block text-sm text-slate-900">{log.summary}</strong><span className="mt-1 block text-xs text-slate-500">対象: {log.entityType} / {log.entityId}</span></div><span className="text-xs font-semibold text-slate-600 sm:text-right">{log.actorName}</span></article>)}</div> : <div className="p-6 text-sm text-slate-500">現在の権限では監査ログを閲覧できません。</div>}</section>
    <ConfirmDialog open={resetOpen} onCancel={() => setResetOpen(false)} onConfirm={handleReset} title="デモデータを初期状態へ戻しますか？" description="このブラウザで行った売上登録、編集、取消、マスタ変更を破棄し、最初の架空データへ戻します。" confirmLabel="初期状態へ戻す" />
  </div>;
}

function InfoCard({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <article className="rounded-2xl border border-black/[0.06] bg-white p-5 shadow-sm"><span className="flex size-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700">{icon}</span><h2 className="mt-4 font-bold">{title}</h2>{children}</article>; }
function PermissionMark({ role, permission }: { role: UserRole; permission: Permission }) { const allowed = roleHasPermission(role, permission); return <span aria-label={allowed ? "許可" : "不可"} className={allowed ? "font-bold text-emerald-700" : "text-slate-300"}>{allowed ? "✓" : "—"}</span>; }
